### ISSUE TITLE
front-end React.JS app needs to be made to work without need for mouse

### ISSUE THREAD

**Issue by medhatelmasry** [medhatelmasry/voting-tool-react#6]
The public-facing React.JS site should be make to work using the keyboard without the use of a mouse.

**Comment by medhatelmasry** [comment]
Come up with a proof of concept.

**Comment by Jovan-23** [comment]
Little progress made would suggest for the next group/developers to look into a library such as this one, as it may make the process much easier:

 https://www.npmjs.com/package/react-navtree

Example from the library above:
https://alexmnv.github.io/react-navtree/basic/

**Comment by TanushParkashVerma** [comment]
Partially Fixed the keyboard issue. my repository got corrupted for some reason and i didn't create pull request since it messed up develop branch today so i created new branch "tanush" and pushed my full code again to "tanush". 
So far i worked on this issue using the link https://www.npmjs.com/package/react-use-key and was able to generate the keyboard input on **Console** on inspecting if you press **"a"** letter from keyboard on sections page, consoles shows its input which is a good start for a proof of concept.
Please download the "tanush" branch zip and check its working.
Files changed is **CandidateCard component** and **pages home index.jsx**
